# declarative manifest to deploy a pod running httpd
# run it with: kubectl apply -f declarative-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: decalrative-pod
spec:
  containers:
    - name: httpdcontainer
      image: httpd
