# declarative manifest to deploy a pod running httpd
# run it with: kubectl apply -f declarative-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: httpdcontainer
      image: httpd
      ports:
      - containerPort: 80
    - name: tomcat
      image: tomcat
      ports:
      - containerPort: 8080
