apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greg-cluster-dev-rolebinding
subjects:
- kind: User
  name: greg
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-developer
  apiGroup: rbac.authorization.k8s.io
