apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: csr-for-greg
spec:
  groups:
  - "system:authenticated"
  usages:
  - client auth
  - digital signature
  - key encipherment
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VaM0psWnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU11RGlqeFVCZXYyY2NVQ3U5ZW1PYUk1aEo0cHBHUUtWL0pzWUk5cW8vVDdMNStyCkNDaXJHZGlrRGo2NjBXZmU5Q1o4ZEV3RmZSakJqb3RJU3g2Y2R4UkNOREJTOU5LTTQ0VzlqanMzNXlDWmpTTTMKT0Rzc2UxWnR5WmVkVzBkTDFiTTBQT2dVRmllbHZtNVNLQVE3SHFkZDVqYk9tcitqRVg2dkt6blJydnB6NEZpUApkUWt0UmViQ0NvdXYzQ051dVMvSGUxckIzNTBvcUFJSlpGV2Y3ZGg4ZHF0ck5iRWNJUFpJY1V0ZnE4OGZVOTIrCnExYk0rSWdCeWxkamVRMi96SFZRUTg5K1AzenMxbUo1R3F0L2JJYit6UStWR3JlaTd4WlViTlZoRGRFUFlnM0oKNDFLYTIxMmErd0R1OTBwSUNzckd4WE5lS3B2QjBTNXBkYXRBK0Y4Q0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQi9VN2FSdjlNODhjK0pkLzdBUEZvVEZ4Y3Q4aFRhL1JoL2lqNmFZV1pTVmhuMlA2RVExeXFTCkpqZWRGQ3lXTFVZZnF2SEtMekRuRDhNV1ZtWUtxRnh0c21sN1Blbko1Nk9zMHhtUEVBWWV4RVlHSWJtVHVDTm4Kd0dEWjdxTzQzbUZPd0pUUkdybHhmcVJ5SWx4NXRVam95UUU0MzU2ckJicTJzMHZTaGtBWlgvNmFIRE9aOUxFcApSQlVDeW1IWUtIRGhJbVZ5YUErSmNJQ090K2YyZGU1V3RwOVNqaWZNWHZuVlZaRGpyVEpleWpPckRCUnBDVXZYClBSLzRPM0VSWFFIZXR6S1FsVDlPTjVyenM1ZFUxa0x1OHlQd1hXbUQvK3hHaG56WVRuTjMxUE5Qb1VRMys5azAKR1k2TFpBZEF5eXFHUnBZVmVMampVaTMrOVJ3d2ZvWTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
