apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpdenvs
spec:
  containers:
  - env:
    - name: NAME
      value: "greg"
    - name: Location
      value: "usa"
    image: httpd
    imagePullPolicy: Always
    name: custom-env-pod
