apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql-env-secrets
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysqlsecret
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysqlsecret
          key: username
    image: mysql
    name: mysql-env-secrets
