apiVersion: v1
kind: Pod
metadata:
  name: nginx-resource-limits
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 0.5
      limits:
        cpu: 1
